### ISSUE TITLE
Corrupted xlsx after write operation

### ISSUE THREAD

**Issue by valasek** [360EntSecGroup-Skylar/excelize#152]
Thank you for your great work on excelize. Reading works like a charm.
But I have an issue with writing.

I update one cell, save and XLSX file is corrupted.

Input file: [source_file.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1465192/source_file.xlsx)
Output corrupted file: [Workbook.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1465193/Workbook.xlsx)

How I am writing to the file
```
xlsx, err := excelize.OpenFile(path)
xlsx.SetCellInt("Sheet1", "I15", 100)
err := xlsx.SaveAs("./Workbook.xlsx")
```
Erro message during opening Workbook.xlsx
![image](https://user-images.githubusercontent.com/1046787/32704428-1b2a20de-c805-11e7-93d3-068349365c9e.png)

And error if I try to recover the workbook:
Replaced Part: /xl/worksheets/sheet1.xml part with XML error.  Load error. Line 2, column 213397.
Removed Records: Formula from /xl/calcChain.xml part (Calculation properties)

go env
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\stanislav.valasek\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

**Comment by cescoferraro** [comment]
Have you tried using SetCellValue?

**Comment by valasek** [comment]
Yes `xlsx.SetCellValue("Sheet1", "I15", 100)`
But if I understand SetCellValue correctly it only switches based on data type and in this case it should call SetCellInt or am I missing something?

Result it the same. Output file - [Workbook.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1467890/Workbook.xlsx)

Output file is smaller by 680Kb and corrupted.

**Comment by xuri** [comment]
@valasek Thanks for your issue. I have fixed it by add missing XML attribute and namespaces.

**Comment by valasek** [comment]
@xuri thank you. I have updated the package and tested. Works better than before.
I am still getting "Removed Feature: View from /xl/worksheets/sheet2.xml part" but after I hit Repair my excel I can see a content. 
Output file size is similar from 61,4Kb to 51,9 Kb.
I will do some more testing and let you know.

**Comment by valasek** [comment]
@xuri I made a diff of extracted xlsx files input and output before any changes/repairs.
Found a difference in files: styles.xml, workbook.xml, workbook.xml.rels, sheet1.xml.
Attached is a diff of relevant files - [diff.txt](https://github.com/360EntSecGroup-Skylar/excelize/files/1477793/diff.txt)

**Comment by xuri** [comment]
Please attach broken and input file if you can.

**Comment by valasek** [comment]
Which contact can I use to share it directly?

**Comment by valasek** [comment]
@xuri thank you. I have updated the package and tested. Now I can open a sheet where one cell was updated using excelize without a warning.
Based on the above I consider this issue as solved. I do not want to close the issue directly without your confirmation.
If I find any other issues I will report.
_Side note: output files are still smaller and I have sent you the input and output files via email._

**Comment by valasek** [comment]
Based on my testing updated excel files are readable and give any further warnings. Closing the issue. Thank you for fixing.

**Comment by ntttrang** [comment]
Hi dev team,
I want to create new excel file from template excel but I encountered the same issue with version 2.1.0 (Stream Writer).
Could you please help me check this issue?

**Comment by xuri** [comment]
Hi @ntttrang, please try to upgrade the library with the master branch code. Ref: #576

**Comment by ntttrang** [comment]
> Hi @ntttrang, please try to upgrade the library with the master branch code. Ref: #576

@xuri : I am a beginner in Golang, so I don't know how to upgrade the library. Is this latest version?

module export_excel_file2

go 1.12

require (
	github.com/360EntSecGroup-Skylar/excelize v1.4.1 // indirect
	github.com/360EntSecGroup-Skylar/excelize/v2 v2.1.0 // indirect
)

I used this command to upgrade library, but this issue is still existed.
`go get -u github.com/360EntSecGroup-Skylar/excelize`

**Comment by xuri** [comment]
@ntttrang please reference issue [#488](https://github.com/360EntSecGroup-Skylar/excelize/issues/488#issuecomment-536395788).

**Comment by ntttrang** [comment]
> @ntttrang please reference issue [#488](https://github.com/360EntSecGroup-Skylar/excelize/issues/488#issuecomment-536395788).

Thank you for your help

**Comment by jograjrathore** [comment]
[Uploading Vehicle Activity Reports-119 -2023-2024.xlsx…]()

hello PLease help me the same issues. file attached for referance.

**Comment by xuri** [comment]
Hi @jograjrathore, thanks for your feedback. Which version of the Go language and Excelize library are you using? what results you received? and what results you expected? Could you follow the issue template and show us a complete, standalone example program or reproducible demo?

**Comment by xuri** [comment]
Hi @jograjrathore, thanks for your feedback. Which version of the Go language and Excelize library are you using? Could you show us a complete, standalone example program or reproducible demo? The file attachment can not download.

**Comment by hibare** [comment]
@xuri I'm facing same problem. I tried example from readme. File is generated but when I try to open, it throws above error.
I'm on version 16.81 on mac

**Comment by xuri** [comment]
Hi @hibare, thanks for your feedback. Which version of the Go language and Excelize library are you using? Could you show us a complete, standalone example program or reproducible demo?
